# Generated by Django 4.1.2 on 2022-10-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='name')),
                ('message', models.CharField(blank=True, max_length=50, null=True, verbose_name='message')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='datetime')),
            ],
        ),
    ]
